### ISSUE TITLE
should add background field and land mask in plot

### ISSUE THREAD

**Issue by gaelforget** [ECCO-Hackweek/EH24-Drifters#2]
https://github.com/ECCO-Hackweek/EH24-Drifters/blob/78bd420cf48e400c86be3c5c6598cb97071857f3/scripts/initial_simulations.jl#L41

For examples, see https://juliaclimate.github.io/MeshArrays.jl/dev/tutorials/geography.html

**Comment by kykinne** [comment]
import Pkg; Pkg.add("MeshArrays")
using MeshArrays

fil=demo.download_polygons("countries.geojson")
pol=MeshArrays.read_polygons(fil);

[lines!(a,l1,color = :white, linewidth = 0.5) for l1 in pol] #0-360 but countries are -180-180


Then also need to transform the particle lon positions -180 so that the grid are the same.

**Comment by YuanyuanSong99** [comment]
![mask_test1](https://github.com/user-attachments/assets/3f97c377-32e0-4977-9ae7-f6b01852ea72)
Perhaps the particle Lon positions should -360

**Comment by gaelforget** [comment]
> import Pkg; Pkg.add("MeshArrays") using MeshArrays
> fil=demo.download_polygons("countries.geojson") pol=MeshArrays.read_polygons(fil);
> [lines!(a,l1,color = :white, linewidth = 0.5) for l1 in pol] #0-360 but countries are -180-180

Nice! Couple notes :

1. seems to need this before : 

```
using MeshArrays, GeoJSON, CairoMakie, DataDeps
fi=Figure(); a=Axis(fi[1,1])
```

2. try `lon180(x)=Float64(x>180.0 ? x-360.0 : x)`

3. when you feel ready, please open a pull request to add this to the repository

**Comment by YuanyuanSong99** [comment]
I added examples_SouthAtlantic1.jl in the directory of scripts, with two ways to add land background. I recommend the second way. Here are figures by both ways.
![mask_test1](https://github.com/user-attachments/assets/c4c43437-189c-4a62-89d0-6a3fd31bb936)
![mask_test2](https://github.com/user-attachments/assets/904698bb-0d71-49c1-9aed-14dc72114804)

**Comment by YuanyuanSong99** [comment]
![mask_test2](https://github.com/user-attachments/assets/15c12b11-d9f1-4178-878d-3a6885409a4d)
Now we have a plot with depth colormap of particles

**Comment by YuanyuanSong99** [comment]
We also have a map using heatmap function
![mask_test3_heatmap](https://github.com/user-attachments/assets/17c54ad1-7d13-47f1-a7c2-dda7d1131412)

**Comment by gaelforget** [comment]
all set then. Thank you all
