### ISSUE TITLE
need Southern Atlantic example

### ISSUE THREAD

**Issue by gaelforget** [ECCO-Hackweek/EH24-Drifters#3]
I suggest to do something like this :

1. create a separate script `example_SouthAtlantic1.jl` that runs after the initial example

```
include("initial_simulations.jl")
include("example_SouthAtlantic1.jl")
```

2. this script may look like this (have not tested)

```
nf=10*1000; lo=(-40.0,30.0); la=(-6.0,-6.0); level=2.5
I=Individuals(P,df.x,df.y,df.z,df.f,(🔴=rec,🔧=proc, 𝐷=D))
T=(0.0,10*10*86400.0)
step_forward!(I,T)
```

where 

- we target a similar region as in https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020GL089137
- we increase duration and the number of particles
- on how to ocean basin mask regions, please see see https://juliaclimate.github.io/MeshArrays.jl/dev/tutorials/geography.html ; we may do something like this below (untested)

**Comment by gaelforget** [comment]
- please verify that the code below is correct before using it
- the choice of 30W as a boundary will eliminate most of the Indian Ocean, to make things simpler and faster for now

```
  using MeshArrays
  basins=demo.ocean_basins()
  AtlExt=demo.extended_basin(basins,:Atl)
  IndExt=demo.extended_basin(basins,:Ind)
  mymask=AtlExt .* (G.XC .> -40.0) .* (G.XC .<=30.0) .* (G.YC .< -6) .* ( G.hFacC[:,1] .> 0.0 )
```

**Comment by ciarapimm** [comment]
Add trajectories from initial point to end point.

**Comment by MaceKuailv** [comment]
Some results with seaduck. 
I am using ECCO releasing from July 15th, 1993. I **don't** have bolus velocity. 

Forward 1yr:
![image](https://github.com/user-attachments/assets/80982103-3a0c-4f82-be8d-b1a511220a49)


Backward 1yr:
![image](https://github.com/user-attachments/assets/424b4443-0349-4e3e-b79f-4b9a2de464fa)

**Comment by MaceKuailv** [comment]
Tracer release looks quite different, 1yr forward:
![image](https://github.com/user-attachments/assets/fd977d5e-23e5-4429-9093-897c95dd2c3e)

Initial condition looks like: 
![image](https://github.com/user-attachments/assets/b9ca47c8-5bb6-441e-9d4d-7b14708d2acf)

**Comment by gaelforget** [comment]
has been done
