### ISSUE TITLE
need example for backward in time integration

### ISSUE THREAD

**Issue by gaelforget** [ECCO-Hackweek/EH24-Drifters#4]
In `examples/worldwide/OCCA_FlowFields.jl` you will find that you can just set `backward_in_time=false` in the setup function.

https://github.com/JuliaClimate/IndividualDisplacements.jl/blob/7f2ae7b8a07001e41b5e44bc91ffddf0f70a0e82/examples/worldwide/OCCA_FlowFields.jl#L11

Does this work?

**Comment by YuanyuanSong99** [comment]
Yes, it work well! Here's the plot integrating backward 365 days.
![backward_test_365](https://github.com/user-attachments/assets/357687fc-e922-49d7-b41e-1af886074df1)

**Comment by YuanyuanSong99** [comment]
And  the plot integrating forward 365 days.
![forward_test_365](https://github.com/user-attachments/assets/5b3c979d-43fc-4f99-a741-d7e6c216f771)

**Comment by gaelforget** [comment]
Great! Thank you
